---
Name: catalogueconfig
---
SiteConfig:
  extensions:
    - CatalogueSiteConfigExtension
Controller:
  extensions:
    - CatalogueControllerExtension
Image:
  extensions:
    - CatalogueImageExtension
LeftAndMain:
  extensions:
    - CatalogueLeftAndMainExtension
