---
Name: catalogueconfig
---
SiteConfig:
  extensions:
    - CatalogueSiteConfigExtension
Controller:
  extensions:
    - CatalogueControllerExtension
Image:
  extensions:
    - CatalogueImageExtension
LeftAndMain:
  extra_requirements_css:
    - catalogue/css/admin.css
