---
Name: cataloguefrontendconfig
---
SilverStripe\Control\Controller:
  extensions:
    - SilverCommerce\CatalogueFrontend\Extensions\ControllerExtension
SilverCommerce\CatalogueAdmin\Model\CatalogueProduct:
  extensions:
    - SilverCommerce\CatalogueFrontend\Extensions\CatalogueLinkExtension
SilverCommerce\CatalogueAdmin\Model\CatalogueCategory:
  extensions:
    - SilverCommerce\CatalogueFrontend\Extensions\CatalogueLinkExtension
---
Only:
  moduleexists: 'silvercommerce/shoppingcart'
---
SilverCommerce\CatalogueFrontend\Control\CatalogueController:
  extensions:
    - SilverCommerce\CatalogueFrontend\Extensions\AddToCartExtension